site_name: ferramentas_scielo_v2
site_url: https://LABHDUFBA.github.io/ferramentas_scielo_v2

theme:
  logo: img/logo.png
  favicon: img/favicon.ico
  name: material 
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Mudar para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Mudar para modo noturno

repo_url: https://github.com/LABHDUFBA/ferramentas_scielo_v2
repo_name: LABHDUFBA/ferramentas_scielo_v2

plugins:
  - git-revision-date

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.superfences

nav:
    - Home: index.md
    - Sobre: about.md
    - Citação: citation.md
    - Licença: license.md 
